global:
  scrape_interval: 10s          # How often to scrape targets
  evaluation_interval: 10s      # How often to evaluate rules

scrape_configs:
  # ------------------------------
  # Prometheus own metrics
  # ------------------------------
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ------------------------------
  # OpenTelemetry Collector metrics
  # ------------------------------
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  # ------------------------------
  # User service metrics
  # ------------------------------
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8002"]  # port of /metrics endpoint

  # ------------------------------
  # Ride service metrics
  # ------------------------------
  - job_name: "ride-service"
    static_configs:
      - targets: ["ride-service:3000"]  # port of /metrics endpoint

  # ------------------------------
  # Vehicle service metrics
  # ------------------------------
  - job_name: "vehicle-service"
    static_configs:
      - targets: ["vehicle-service:6000"]

  # ------------------------------
  # Payment service metrics
  # ------------------------------
  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:7000"]

  # ------------------------------
  # Notification service metrics
  # ------------------------------
  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8000"]